/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_affichage (void);
GtkWidget* create_remplissage (void);
GtkWidget* create_supprimer (void);
GtkWidget* create_modifier (void);
GtkWidget* create_stat (void);
